/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.ProdukController;
import util.FormatRupiah;
import util.Validator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author FADHIL
 */
public class Produk extends javax.swing.JFrame {
    private final ProdukController controller = new ProdukController();
    private DefaultTableModel modelTabel;
    private int idProdukTerpilih = -1;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Produk.class.getName());

    /**
     * Creates new form Produk
     */
public Produk() {

    initComponents();

    setTitle("Data Produk");
    setLocationRelativeTo(null);

    modelTabel = (DefaultTableModel) TableProduk.getModel();

    TableProduk.getSelectionModel().addListSelectionListener(e -> {

        if (!e.getValueIsAdjusting()) {
            isiForm();
        }

    });

    muatDataProduk();

}

    

private void tampilkanKeTabel(List<model.Produk> daftarProduk) {

    modelTabel.setRowCount(0);

    for (model.Produk p : daftarProduk) {

        modelTabel.addRow(new Object[]{

            p.getIdProduk(),
            p.getKodeProduk(),
            p.getNamaProduk(),
            FormatRupiah.format(p.getHarga()),
            p.getStok(),
            p.getKategori()

        });

    }

}


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        InputCariProduk = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ButtonCari = new javax.swing.JButton();
        ButtonRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableProduk = new javax.swing.JTable();
        InputKodeProduk = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        InputKategori = new javax.swing.JTextField();
        InputStok = new javax.swing.JTextField();
        InputNamaProduk = new javax.swing.JTextField();
        InputHarga = new javax.swing.JTextField();
        ButtonTambahkan = new javax.swing.JButton();
        ButtonEdit = new javax.swing.JButton();
        ButtonHapus = new javax.swing.JButton();
        ButtonBersihkan = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton5.setText("Hapus");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InputCariProduk.addActionListener(this::InputCariProdukActionPerformed);

        jLabel1.setText("Cari Produk    :");

        ButtonCari.setText("CARI");
        ButtonCari.addActionListener(this::ButtonCariActionPerformed);

        ButtonRefresh.setText("REFRESH");
        ButtonRefresh.addActionListener(this::ButtonRefreshActionPerformed);

        TableProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Kode", "Nama", "Harga", "Stok", "Kategori"
            }
        ));
        jScrollPane1.setViewportView(TableProduk);
        if (TableProduk.getColumnModel().getColumnCount() > 0) {
            TableProduk.getColumnModel().getColumn(0).setHeaderValue("ID");
            TableProduk.getColumnModel().getColumn(1).setHeaderValue("Kode");
            TableProduk.getColumnModel().getColumn(2).setHeaderValue("Nama");
            TableProduk.getColumnModel().getColumn(3).setHeaderValue("Harga");
            TableProduk.getColumnModel().getColumn(4).setHeaderValue("Stok");
            TableProduk.getColumnModel().getColumn(5).setHeaderValue("Kategori");
        }

        InputKodeProduk.addActionListener(this::InputKodeProdukActionPerformed);

        jLabel2.setText("Kode Produk       :");

        jLabel3.setText("Nama Produk     :");

        jLabel4.setText("Harga                  :");

        jLabel5.setText("Stok                     :");

        jLabel6.setText("Kategori              :");

        InputKategori.addActionListener(this::InputKategoriActionPerformed);

        InputStok.addActionListener(this::InputStokActionPerformed);

        InputNamaProduk.addActionListener(this::InputNamaProdukActionPerformed);

        InputHarga.addActionListener(this::InputHargaActionPerformed);

        ButtonTambahkan.setText("Tambahkan");
        ButtonTambahkan.addActionListener(this::ButtonTambahkanActionPerformed);

        ButtonEdit.setText("Edit");
        ButtonEdit.addActionListener(this::ButtonEditActionPerformed);

        ButtonHapus.setText("Hapus");
        ButtonHapus.addActionListener(this::ButtonHapusActionPerformed);

        ButtonBersihkan.setText("Bersihkan");
        ButtonBersihkan.addActionListener(this::ButtonBersihkanActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InputCariProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(ButtonCari)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonRefresh))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ButtonTambahkan)
                                        .addGap(18, 18, 18)
                                        .addComponent(ButtonEdit)
                                        .addGap(18, 18, 18)
                                        .addComponent(ButtonHapus)
                                        .addGap(18, 18, 18)
                                        .addComponent(ButtonBersihkan))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(InputKodeProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel6)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(InputKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(InputStok, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(InputNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(InputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 362, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonCari)
                        .addComponent(InputCariProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonRefresh))
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputKodeProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(InputNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(InputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(InputStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(InputKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonTambahkan)
                    .addComponent(ButtonEdit)
                    .addComponent(ButtonHapus)
                    .addComponent(ButtonBersihkan))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputCariProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputCariProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputCariProdukActionPerformed

    private void ButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCariActionPerformed
        try {

            tampilkanKeTabel(

                    controller.cariProduk(
                        InputCariProduk.getText()
                    )

            );

        }

        catch(Exception ex){

            JOptionPane.showMessageDialog(this,
                    ex.getMessage());

        }        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCariActionPerformed

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
if(idProdukTerpilih==-1){

        JOptionPane.showMessageDialog(this,
                "Pilih data terlebih dahulu.");

        return;

    }

    try{

        controller.perbaruiProduk(

                idProdukTerpilih,

                InputKodeProduk.getText(),

                InputNamaProduk.getText(),

                Validator.parseDouble(InputHarga.getText(),"Harga"),

                Validator.parseInt(InputStok.getText(),"Stok"),

                InputKategori.getText()

        );

        JOptionPane.showMessageDialog(this,
                "Produk berhasil diubah.");

        bersihkanForm();

        muatDataProduk();

    }

    catch(Exception ex){

        JOptionPane.showMessageDialog(this,
                ex.getMessage());

    }
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEditActionPerformed

    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
if(idProdukTerpilih==-1){

        JOptionPane.showMessageDialog(this,
                "Pilih data terlebih dahulu.");

        return;

    }

    int pilih = JOptionPane.showConfirmDialog(

            this,

            "Yakin ingin menghapus produk?",

            "Konfirmasi",

            JOptionPane.YES_NO_OPTION

    );

    if(pilih==JOptionPane.YES_OPTION){

        try{

            controller.hapusProduk(idProdukTerpilih);

            JOptionPane.showMessageDialog(this,
                    "Produk berhasil dihapus.");

            bersihkanForm();

            muatDataProduk();

        }

        catch(Exception ex){

            JOptionPane.showMessageDialog(this,
                    ex.getMessage());

        }

    }
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonHapusActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ButtonBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBersihkanActionPerformed
    bersihkanForm();        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonBersihkanActionPerformed

    private void InputKodeProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputKodeProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputKodeProdukActionPerformed

    private void ButtonTambahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahkanActionPerformed
try {

        controller.tambahProduk(

                InputKodeProduk.getText(),

                InputNamaProduk.getText(),

                Validator.parseDouble(InputHarga.getText(),"Harga"),

                Validator.parseInt(InputStok.getText(),"Stok"),

                InputKategori.getText()

        );

        JOptionPane.showMessageDialog(this,
                "Produk berhasil ditambahkan.");

        bersihkanForm();

        muatDataProduk();

    } catch (Exception ex) {

        JOptionPane.showMessageDialog(this,
                ex.getMessage());

    }        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonTambahkanActionPerformed

    private void ButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRefreshActionPerformed
    InputCariProduk.setText("");

    muatDataProduk();
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonRefreshActionPerformed

    private void InputNamaProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNamaProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNamaProdukActionPerformed

    private void InputHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputHargaActionPerformed

    private void InputStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputStokActionPerformed

    private void InputKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputKategoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Produk().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBersihkan;
    private javax.swing.JButton ButtonCari;
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonRefresh;
    private javax.swing.JButton ButtonTambahkan;
    private javax.swing.JTextField InputCariProduk;
    private javax.swing.JTextField InputHarga;
    private javax.swing.JTextField InputKategori;
    private javax.swing.JTextField InputKodeProduk;
    private javax.swing.JTextField InputNamaProduk;
    private javax.swing.JTextField InputStok;
    private javax.swing.JTable TableProduk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

private void isiForm() {

    int row = TableProduk.getSelectedRow();

    if (row == -1)
        return;

    idProdukTerpilih = Integer.parseInt(
            modelTabel.getValueAt(row,0).toString());

    InputKodeProduk.setText(modelTabel.getValueAt(row,1).toString());

    InputNamaProduk.setText(modelTabel.getValueAt(row,2).toString());

    InputHarga.setText(
            modelTabel.getValueAt(row,3)
                    .toString()
                    .replaceAll("[^0-9]", "")
    );

    InputStok.setText(modelTabel.getValueAt(row,4).toString());

    InputKategori.setText(modelTabel.getValueAt(row,5).toString());

}

private void muatDataProduk() {

    try {

        tampilkanKeTabel(controller.semuaProduk());

    } catch (Exception ex) {

        JOptionPane.showMessageDialog(this,
                ex.getMessage());

    }

}

    private void bersihkanForm() {
    idProdukTerpilih = -1;

    InputKodeProduk.setText("");

    InputNamaProduk.setText("");

    InputHarga.setText("");

    InputStok.setText("");

    InputKategori.setText("");

    TableProduk.clearSelection();
    
    }

}
